/**
 * Created by sioxa on 2017/3/17 0017.
 */
export default {
    /**ACTION 获取机床详细信息 */
    GET_MACHINE_DETAIL:'GET_MACHINE_DETAIL',
    /**ACTION 获取机床状态 */
    GET_PLANT_STATUS:'GET_PLANT_STATUS',

    /**MUTATION 关闭机床详情面板 */
    CLOSE_MACHINE_DETAIL_PANNEL:'CLOSE_MACHINE_DETAIL_PANNEL',
    /**MUTATION 打开机床详情面板 */
    OPEN_MACHINE_DETAIL_PANNEL:'OPEN_MACHINE_DETAIL_PANNEL'
}